### ISSUE TITLE
Issue after downloading first model (get stuck)

### ISSUE THREAD

**Issue by gioxyer** [huggingface/meshgen#11]
After the download as ai model, it gets stuck and if you reload blender give this issue (both version cpu and cuda):

TBBmalloc: skip allocation functions replacement in ucrtbase.dll: unknown prologue for function _msize
Add-on not loaded: "bl_ext.user_default.blenderkit", cause: No module named 'bl_ext.user_default.blenderkit'
Loading generator...
Failed to load generator: Failed to load shared library 'C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\meshgen\.python_dependencies\llama_cpp\lib\llama.dll': Could not find module 'C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\meshgen\.python_dependencies\llama_cpp\lib\llama.dll' (or one of its dependencies). Try using the full path with constructor syntax.
Traceback (most recent call last):
  File "C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\meshgen\.python_dependencies\llama_cpp\llama_cpp.py", line 75, in _load_shared_library
    return ctypes.CDLL(str(_lib_path), **cdll_args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\meshgen\.python_dependencies\llama_cpp\lib\llama.dll' (or one of its dependencies). Try using the full path with constructor syntax.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\meshgen\generator\generator.py", line 72, in load_generator
    import llama_cpp
  File "C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\meshgen\.python_dependencies\llama_cpp\__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\meshgen\.python_dependencies\llama_cpp\llama_cpp.py", line 88, in <module>
    _lib = _load_shared_library(_lib_base_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\meshgen\.python_dependencies\llama_cpp\llama_cpp.py", line 77, in _load_shared_library
    raise RuntimeError(f"Failed to load shared library '{_lib_path}': {e}")
RuntimeError: Failed to load shared library 'C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\meshgen\.python_dependencies\llama_cpp\lib\llama.dll': Could not find module 'C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\meshgen\.python_dependencies\llama_cpp\lib\llama.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by takeraparterer** [comment]
Same issue, using blender 4.3.0

**Comment by gioxyer** [comment]
They suggest Blender 4.2, I tested with both 4.2 and 4.3 same issue, the version before doesn't give to me that problem, only vram issue, but now that I have requirements give this error

**Comment by gioxyer** [comment]
![immagine](https://github.com/user-attachments/assets/564493ba-244d-4f54-b3cc-ff63b71f2ae0)

**Comment by gioxyer** [comment]
Fixed by reinstall CUDA 12.1

**Comment by StaiMerr** [comment]
Still have this issue, reinstall didnt help
