### ISSUE TITLE
Meshgen-cpu-win64 Installation Error on Blender 4.3

### ISSUE THREAD

**Issue by andrewg259** [huggingface/meshgen#18]
I get this error in my output whenever I attempt to install meshgen to blender, I have tested this on both 4.2, and 4.3 versions and end up with the same result

Python: Traceback (most recent call last):
  File "F:\SteamLibrary\steamapps\common\Blender\4.3\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 1481, in execute
    cmd_batch = self.exec_command_iter(is_modal)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\SteamLibrary\steamapps\common\Blender\4.3\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 2560, in exec_command_iter
    self.exec_legacy(source_filepath)
  File "F:\SteamLibrary\steamapps\common\Blender\4.3\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 2692, in exec_legacy
    bpy.types.PREFERENCES_OT_addon_install.execute(self, bpy.context)
  File "F:\SteamLibrary\steamapps\common\Blender\4.3\scripts\startup\bl_operators\userpref.py", line 813, in execute
    bpy.ops.preferences.addon_enable(module=mod.__name__)
  File "F:\SteamLibrary\steamapps\common\Blender\4.3\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: No module named 'meshgen.preferences'

**Comment by dylanebert** [comment]
Is it now working in the latest release?
