### ISSUE TITLE
Cant load model BUG

### ISSUE THREAD

**Issue by StaiMerr** [huggingface/meshgen#19]
TBBmalloc: skip allocation functions replacement in ucrtbase.dll: unknown prologue for function _msize
Repository data: C:\Users\xdvor\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org not found, sync required!
Loading generator...
Failed to load generator: Failed to load shared library 'C:\Users\xdvor\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\meshgen\.python_dependencies\llama_cpp\lib\llama.dll': Could not find module 'C:\Users\xdvor\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\meshgen\.python_dependencies\llama_cpp\lib\llama.dll' (or one of its dependencies). Try using the full path with constructor syntax.
Traceback (most recent call last):
  File "C:\Users\xdvor\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\meshgen\.python_dependencies\llama_cpp\llama_cpp.py", line 75, in _load_shared_library
    return ctypes.CDLL(str(_lib_path), **cdll_args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.2\python\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'C:\Users\xdvor\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\meshgen\.python_dependencies\llama_cpp\lib\llama.dll' (or one of its dependencies). Try using the full path with constructor syntax.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xdvor\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\meshgen\generator\generator.py", line 80, in load_generator
    import llama_cpp
  File "C:\Users\xdvor\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\meshgen\.python_dependencies\llama_cpp\__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "C:\Users\xdvor\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\meshgen\.python_dependencies\llama_cpp\llama_cpp.py", line 88, in <module>
    _lib = _load_shared_library(_lib_base_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xdvor\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\meshgen\.python_dependencies\llama_cpp\llama_cpp.py", line 77, in _load_shared_library
    raise RuntimeError(f"Failed to load shared library '{_lib_path}': {e}")
RuntimeError: Failed to load shared library 'C:\Users\xdvor\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\meshgen\.python_dependencies\llama_cpp\lib\llama.dll': Could not find module 'C:\Users\xdvor\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\meshgen\.python_dependencies\llama_cpp\lib\llama.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by Darthph0enix7** [comment]
i just reimported the addon and it fixed it
