### ISSUE TITLE
Nothing happens after generate mesh button is clicked

### ISSUE THREAD

**Issue by madeleinelmuller** [huggingface/meshgen#8]
I’ve been waiting for almost four hours, and nothing has happened yet. I still have zero vertices, edges, etc. Yes, I do have the dependencies.

**Comment by madeleinelmuller** [comment]
> What is the output in the console?

bpy.ops.meshgen.load_generator()

**Comment by mak448a** [comment]
Same problem.
```
Failed to load generator: Failed to load shared library '/home/user/.config/blender/4.2/scripts/addons/meshgen/.python_dependencies/llama_cpp/lib/libllama.so': libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/user/.config/blender/4.2/scripts/addons/meshgen/.python_dependencies/llama_cpp/llama_cpp.py", line 75, in _load_shared_library
    return ctypes.CDLL(str(_lib_path), **cdll_args)  # type: ignore
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/ctypes/__init__.py", line 390, in __init__
    self._handle = _dlopen(self._name, mode)
                   ~~~~~~~^^^^^^^^^^^^^^^^^^
OSError: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.config/blender/4.2/scripts/addons/meshgen/generator/generator.py", line 80, in load_generator
    import llama_cpp
  File "/home/user/.config/blender/4.2/scripts/addons/meshgen/.python_dependencies/llama_cpp/__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "/home/user/.config/blender/4.2/scripts/addons/meshgen/.python_dependencies/llama_cpp/llama_cpp.py", line 88, in <module>
    _lib = _load_shared_library(_lib_base_name)
  File "/home/user/.config/blender/4.2/scripts/addons/meshgen/.python_dependencies/llama_cpp/llama_cpp.py", line 77, in _load_shared_library
    raise RuntimeError(f"Failed to load shared library '{_lib_path}': {e}")
RuntimeError: Failed to load shared library '/home/user/.config/blender/4.2/scripts/addons/meshgen/.python_dependencies/llama_cpp/lib/libllama.so': libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
```

**Comment by dylanebert** [comment]
This may be due to llama-cpp-python looking for a C++ compiler on your system

You can try installing Visual Studio with Desktop development with C++ and see if it fixes it

**Comment by dylanebert** [comment]
@mak448a you may be able to try the solution here https://github.com/alexander-akhmetov/python-telegram/issues/3#issuecomment-438061449

```
apt-get install musl-dev
ln -s /usr/lib/x86_64-linux-musl/libc.so /lib/libc.musl-x86_64.so.1
```

**Comment by mak448a** [comment]
Hi @dylanebert, after installing musl-devel (dnf) and using ln, it still produced the error. Do you know how to fix this?
